# Generated by Django 2.0.13 on 2019-04-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.CharField(choices=[('vijayanagar', 'omega hospitals,vijayanagar'), ('jayanagar', 'omega hospitals,jayanagr'), ('girinagar', 'omega hospitals,girinagar')], default='girinagar', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='speciality',
            field=models.CharField(choices=[('cardiology', 'cardiology'), ('oncology', 'oncology'), ('dermetalogy', 'dermetalogy'), ('gynecology', 'gynecology'), ('pediatrics', 'pediatrics'), ('ENT', 'ENT')], default='pediatrcis', max_length=30),
        ),
    ]
