# Generated by Django 2.0.13 on 2019-04-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20190416_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='apt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateTimeField()),
                ('age', models.PositiveSmallIntegerField()),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('email', models.EmailField(max_length=70)),
                ('hospital', models.CharField(choices=[('jayanagar', 'omega hospitals,jayanagr'), ('vijayanagar', 'omega hospitals,vijayanagar'), ('girinagar', 'omega hospitals,girinagar')], default='girinagar', max_length=30)),
                ('speciality', models.CharField(choices=[('dermetalogy', 'dermetalogy'), ('oncology', 'oncology'), ('cardiology', 'cardiology'), ('gynecology', 'gynecology'), ('ENT', 'ENT'), ('pediatrics', 'pediatrics')], default='pediatrcis', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
