# Generated by Django 2.0.13 on 2019-04-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20190417_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt',
            name='hospital',
            field=models.CharField(choices=[('girinagar', 'omega hospitals,girinagar'), ('vijayanagar', 'omega hospitals,vijayanagar'), ('jayanagar', 'omega hospitals,jayanagr')], default='girinagar', max_length=30),
        ),
        migrations.AlterField(
            model_name='apt',
            name='speciality',
            field=models.CharField(choices=[('ENT', 'ENT'), ('pediatrics', 'pediatrics'), ('oncology', 'oncology'), ('gynecology', 'gynecology'), ('dermetalogy', 'dermetalogy'), ('cardiology', 'cardiology')], default='pediatrcis', max_length=30),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=50),
        ),
    ]
