# Generated by Django 2.0.13 on 2019-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20190417_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt',
            name='hospital',
            field=models.CharField(choices=[('girinagar', 'omega hospitals,girinagar'), ('jayanagar', 'omega hospitals,jayanagr'), ('vijayanagar', 'omega hospitals,vijayanagar')], default='girinagar', max_length=30),
        ),
        migrations.AlterField(
            model_name='apt',
            name='speciality',
            field=models.CharField(choices=[('cardiology', 'cardiology'), ('pediatrics', 'pediatrics'), ('gynecology', 'gynecology'), ('oncology', 'oncology'), ('dermetalogy', 'dermetalogy'), ('ENT', 'ENT')], default='pediatrcis', max_length=30),
        ),
    ]
