# Generated by Django 2.0.13 on 2019-04-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20190417_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt',
            name='hospital',
            field=models.CharField(choices=[('jayanagar', 'omega hospitals,jayanagr'), ('girinagar', 'omega hospitals,girinagar'), ('vijayanagar', 'omega hospitals,vijayanagar')], default='girinagar', max_length=30),
        ),
        migrations.AlterField(
            model_name='apt',
            name='speciality',
            field=models.CharField(choices=[('dermetalogy', 'dermetalogy'), ('gynecology', 'gynecology'), ('pediatrics', 'pediatrics'), ('ENT', 'ENT'), ('oncology', 'oncology'), ('cardiology', 'cardiology')], default='pediatrcis', max_length=30),
        ),
    ]
