# Generated by Django 2.0.13 on 2019-04-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_auto_20190418_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt',
            name='hospital',
            field=models.CharField(choices=[('vijayanagar', 'omega hospitals,vijayanagar'), ('jayanagar', 'omega hospitals,jayanagr'), ('girinagar', 'omega hospitals,girinagar')], default='girinagar', max_length=30),
        ),
        migrations.AlterField(
            model_name='apt',
            name='speciality',
            field=models.CharField(choices=[('oncology', 'oncology'), ('ENT', 'ENT'), ('cardiology', 'cardiology'), ('dermetalogy', 'dermetalogy'), ('gynecology', 'gynecology'), ('pediatrics', 'pediatrics')], default='pediatrcis', max_length=30),
        ),
    ]
