# Generated by Django 2.0.13 on 2019-04-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_auto_20190418_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt',
            name='hospital',
            field=models.CharField(choices=[('vijayanagar', 'omega hospitals,vijayanagar'), ('girinagar', 'omega hospitals,girinagar'), ('jayanagar', 'omega hospitals,jayanagr')], default='girinagar', max_length=30),
        ),
        migrations.AlterField(
            model_name='apt',
            name='speciality',
            field=models.CharField(choices=[('dermetalogy', 'dermetalogy'), ('oncology', 'oncology'), ('ENT', 'ENT'), ('gynecology', 'gynecology'), ('pediatrics', 'pediatrics'), ('cardiology', 'cardiology')], default='pediatrcis', max_length=30),
        ),
    ]
