# Generated by Django 2.0.13 on 2019-04-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_auto_20190418_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt',
            name='hospital',
            field=models.CharField(choices=[('jayanagar', 'omega hospitals,jayanagr'), ('girinagar', 'omega hospitals,girinagar'), ('vijayanagar', 'omega hospitals,vijayanagar')], default='girinagar', max_length=30),
        ),
        migrations.AlterField(
            model_name='apt',
            name='speciality',
            field=models.CharField(choices=[('cardiology', 'cardiology'), ('oncology', 'oncology'), ('pediatrics', 'pediatrics'), ('ENT', 'ENT'), ('dermetalogy', 'dermetalogy'), ('gynecology', 'gynecology')], default='pediatrcis', max_length=30),
        ),
    ]
