# Generated by Django 2.0.13 on 2019-04-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_auto_20190418_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='apt',
            name='speciality',
            field=models.CharField(choices=[('cardiology', 'cardiology'), ('gynecology', 'gynecology'), ('pediatrics', 'pediatrics'), ('dermetalogy', 'dermetalogy'), ('ENT', 'ENT'), ('oncology', 'oncology')], default='pediatrcis', max_length=30),
        ),
    ]
