# Generated by Django 2.0.13 on 2019-04-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_auto_20190421_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt',
            name='hospital',
            field=models.CharField(choices=[('vijayanagar', 'omega hospitals,vijayanagar'), ('girinagar', 'omega hospitals,girinagar'), ('jayanagar', 'omega hospitals,jayanagr')], default='girinagar', max_length=30),
        ),
        migrations.AlterField(
            model_name='apt',
            name='speciality',
            field=models.CharField(choices=[('gynecology', 'gynecology'), ('pediatrics', 'pediatrics'), ('dermetalogy', 'dermetalogy'), ('oncology', 'oncology'), ('cardiology', 'cardiology'), ('ENT', 'ENT')], default='pediatrcis', max_length=30),
        ),
    ]
