# Generated by Django 2.0.13 on 2019-04-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20190421_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt',
            name='hospital',
            field=models.CharField(choices=[('vijayanagar', 'omega hospitals,vijayanagar'), ('jayanagar', 'omega hospitals,jayanagr'), ('girinagar', 'omega hospitals,girinagar')], default='girinagar', max_length=30),
        ),
        migrations.AlterField(
            model_name='apt',
            name='speciality',
            field=models.CharField(choices=[('cardiology', 'cardiology'), ('ENT', 'ENT'), ('pediatrics', 'pediatrics'), ('dermetalogy', 'dermetalogy'), ('gynecology', 'gynecology'), ('oncology', 'oncology')], default='pediatrcis', max_length=30),
        ),
    ]
